website/__init__.py
from flask import Flask

def create_app() -> Flask:
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'testing1473'

    from .views import views

    app.register_blueprint(views, url_prefix="/")

    return app

website/views.py
from flask import Blueprint, render_template, request, redirect
import os
import csv
import pandas as pd

views = Blueprint('views', __name__)


##########################################
# Function to get images from the folder #
##########################################
def get_images(typ=None, lang="en") -> dict:
    if type == None: return None

    path = os.path.join(os.getcwd(), "website", "static", "images", typ)
    dir_list = sorted(os.listdir(path))
    res = {}
    trans_words = []
    trans_file_path = ""

    if lang == "hin":
        os.path.join(".", "website", "static", "data", "hindi.csv")
        trans_file_path = os.path.join(".", "website", "static", "data", "hindi.csv")
    elif lang == "tel":
        trans_file_path = os.path.join(".", "website", "static", "data", "telugu.csv")
    elif lang == "tam":
        trans_file_path = os.path.join(".", "website", "static", "data", "tamil.csv")
    elif lang == "mal":
        trans_file_path = os.path.join(".", "website", "static", "data", "malayalam.csv")
        
    file = pd.read_csv(trans_file_path, encoding="utf-8")
    print()
        
    if typ == "objects":
        trans_words = file["Object"].to_list()
    elif typ == "food":
        trans_words = file["Food"].to_list()
    elif typ == "animals":
        trans_words = file["Animal"].to_list()


    print("\n".join(i.split(".")[0] for i in dir_list))

    for file, trans_word in zip(dir_list, trans_words):
        file_path = f"/images/{typ}/{file}"
        word = file.split(".")[0].capitalize()

        res[word] = [trans_word, file_path]


    return res



#######################
# Route to index page #
#######################
@views.route("/")
def index():
    return render_template("index.html")



#######################
# Route to learn page #
#######################
@views.route("/learn", methods=["POST", "GET"])
def learn():
    result = {}

    if request.method == 'POST':
        res = request.form

        language = res["lang"]
        learn_type = res["button"]


        if language == "Hindi": language = "hin"
        elif language == "Telugu": language = "tel"
        elif language == "Tamil": language = "tam"
        elif language == "Malayalam": language = "mal"

        
        print(language, learn_type)

        result = get_images(learn_type, lang=language)
        return render_template("learn.html", result=result)
    else:
        return redirect("/")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static', filename='base.css') }}">
    {% block style_scripts %}{% endblock %}
</head>
<body>
	<div class="navbar">
		<li>
			<ul>
				<a href="/" id="heading">Flash Card Learning</a>
			</ul>
			<ul>
				{% block selectMenu %}
				{% endblock %}
			</ul>
		</li>
	</div>

    <!-- <div class="flashcard">
      <div class="front">
        <h2>Front Side</h2>
        <p>This is the front side of the flashcard.</p>
      </div>
      <div class="back">
        <h2>Back Side</h2>
        <p>This is the back side of the flashcard.</p>
      </div>
    </div> -->

		<div class="content">
			{% block content %}
			{% endblock %}
		</div>
	</form>
</body>
</html>

website/templates/index.html
{% extends "base.html" %}

{% block selectMenu %}

<select name="lang" id="select" form="main-form">
    <option value="Hindi">Hindi</option>
    <option value="Malayalam">Malayalam</option>
    <option value="Tamil">Tamil</option>
    <option value="Telugu">Telugu</option>
</select>

{% endblock %}

{% block content %}

<div class="category-holder">
    <form class="body-cont" action="{{ url_for('views.learn') }}" id="main-form" method="POST">
        <div class="cat">
            <span>Objects</span>
            <button type="submit" name="button" value="objects">
                Start Learning
            </button>
        </div>
    
        <div class="cat">
            <span>Food</span>
            <button type="submit" name="button" value="food">
                Start Learning
            </button>
        </div>
    
        <div class="cat">
            <span>Animals</span>
            <button type="submit" name="button" value="animals">
                Start Learning
            </button>
        </div>
    </form>
</div>

{% endblock %}

website/templates/learn.html
{% extends "base.html" %}

{% block content %}

<div class="flashcards">

    <div class="arrow arrowl">
        <a href="#" onclick="plusSlides(-1)">&#x203A;</a>
    </div>

    <div class="fc">
        <div class="spacer"></div>
        {% for key, value in result.items() %}
        <div class="main-fc">
            <div class="fc-inner">
                <div class="fc-front">
                    <div class="img">
                        <img src="{{ url_for('static', filename=value[1]) }}" alt="">
                    </div>
                    <h1 class="image-name">
                        {{ value[0] }}
                    </h1>
                </div>
                <div class="fc-back">
                    <h1 class="image-name">
                        {{ key }}
                    </h1>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="spacer"></div>
    </div>

    <div class="arrow arrowr">
        <a href="#" onclick="plusSlides(1)">&#x203A;</a>
    </div>

</div>


<script>
    let slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }
      
    function showSlides(n) {
        let i;
        let slides = document.getElementsByClassName("main-fc");
        if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[slideIndex-1].style.display = "block";
    }
    
</script>

{% endblock %}